#ifndef MAIN_SCENE_CFG_H
#define MAIN_SCENE_CFG_H

#define MAIN_SCENE_TILE_X (11)
#define MAIN_SCENE_TILE_Y (11)
#define MAIN_SCENE_TILE_BUFF_SIZE (MAIN_SCENE_TILE_Y * MAIN_SCENE_TILE_X)

#endif // MAIN_SCENE_CFG_H
